apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cirros-datavolume
  namespace: acm-discovered-vm
  labels:
    drapp: dr-vm
spec:
  source:
    http:
      url: "https://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: ocs-storagecluster-ceph-rbd  # Assurez-vous que ce StorageClass existe sur cluster1
