apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cnv-install-policy
  namespace: open-cluster-management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    # 1. Créer le Namespace openshift-cnv
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-openshift-cnv-namespace
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-cnv
    # 2. Créer l'OperatorGroup
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-cnv-operatorgroup
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            include:
              - openshift-cnv
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: kubevirt-hyperconverged-group
                  namespace: openshift-cnv
                spec:
                  targetNamespaces:
                    - openshift-cnv
    # 3. Créer la Subscription pour CNV
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-cnv-subscription
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            include:
              - openshift-cnv
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: hco-operatorhub
                  namespace: openshift-cnv
                spec:
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  name: kubevirt-hyperconverged
                  startingCSV: kubevirt-hyperconverged-operator.v4.16.2
                  channel: "stable"
    # 4. Créer l'instance HyperConverged
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-hyperconverged-cr
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            include:
              - openshift-cnv
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: hco.kubevirt.io/v1beta1
                kind: HyperConverged
                metadata:
                  name: kubevirt-hyperconverged
                  namespace: openshift-cnv
                spec: {}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: cnv-install-placementbinding
  namespace: open-cluster-management
placementRef:
  kind: PlacementRule
  name: cnv-install-placementrule
  apiGroup: apps.open-cluster-management.io
subjects:
  - kind: Policy
    name: cnv-install-policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cnv-install-placementrule
  namespace: open-cluster-management
spec:
  clusterSelector:
    matchLabels:
      cluster.open-cluster-management.io/clusterset: saq-dr
